-- 0006 — invitations
--
-- The raw invite token is generated by the backend, emailed, and never
-- stored. Only its SHA-256 lives here, so a database leak does not hand
-- the attacker a set of working invitations. sha256() is core Postgres
-- (11+), no extension required.

create table public.invitations (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references public.organizations (id) on delete cascade,
  email       text not null check (position('@' in email) > 1),
  role        public.org_role not null default 'member',
  token_hash  text not null,
  invited_by  uuid references public.profiles (id) on delete set null,
  expires_at  timestamptz not null,
  accepted_at timestamptz,
  accepted_by uuid references public.profiles (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create unique index invitations_token_hash_key on public.invitations (token_hash);

-- At most one live invitation per email per org. Accepted/expired rows
-- stay as an audit trail and are excluded from the constraint.
create unique index invitations_pending_email_key
  on public.invitations (org_id, lower(email))
  where accepted_at is null;

create index invitations_org_id_idx on public.invitations (org_id);

create trigger invitations_set_updated_at
  before update on public.invitations
  for each row execute function public.set_updated_at();

alter table public.invitations enable row level security;
alter table public.invitations force row level security;

-- Only org admins touch this table directly. The invitee never selects
-- from it — they redeem through accept_invitation() below, which means a
-- token cannot be enumerated by querying the table.
create policy invitations_select_admins
  on public.invitations for select to authenticated
  using (public.has_org_role(org_id, 'owner'::public.org_role, 'admin'::public.org_role));

create policy invitations_insert_admins
  on public.invitations for insert to authenticated
  with check (
    public.has_org_role(org_id, 'owner'::public.org_role, 'admin'::public.org_role)
    and (
      role <> 'owner'::public.org_role
      or public.has_org_role(org_id, 'owner'::public.org_role)
    )
  );

create policy invitations_update_admins
  on public.invitations for update to authenticated
  using (public.has_org_role(org_id, 'owner'::public.org_role, 'admin'::public.org_role))
  with check (public.has_org_role(org_id, 'owner'::public.org_role, 'admin'::public.org_role));

create policy invitations_delete_admins
  on public.invitations for delete to authenticated
  using (public.has_org_role(org_id, 'owner'::public.org_role, 'admin'::public.org_role));

-- ---------------------------------------------------------------------
-- Redemption.
--
-- SECURITY DEFINER because the invitee has, by definition, no membership
-- in the org yet and so no policy can let them read the invitation or
-- write the membership. The function is the only door, and it checks:
-- authenticated, token matches, not already used, not expired, and the
-- email on the invite matches the session's own profile.
--
-- That last check is what stops a token leaked in a forwarded email from
-- being redeemed by whoever received it.
-- ---------------------------------------------------------------------

create or replace function public.accept_invitation(p_token text)
returns public.memberships
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid         uuid := (select auth.uid());
  v_email       text;
  v_token_hash  text;
  v_inv         public.invitations;
  v_membership  public.memberships;
begin
  if v_uid is null then
    raise exception 'authentication required'
      using errcode = 'insufficient_privilege';
  end if;

  if p_token is null or btrim(p_token) = '' then
    raise exception 'invitation token is required'
      using errcode = 'invalid_parameter_value';
  end if;

  v_token_hash := encode(sha256(convert_to(p_token, 'utf8')), 'hex');

  select p.email into v_email
  from public.profiles p
  where p.id = v_uid;

  -- FOR UPDATE so two concurrent redemptions of the same token cannot
  -- both pass the accepted_at check.
  select * into v_inv
  from public.invitations i
  where i.token_hash = v_token_hash
  for update;

  if not found then
    raise exception 'invitation not found'
      using errcode = 'no_data_found';
  end if;

  if v_inv.accepted_at is not null then
    raise exception 'invitation has already been used'
      using errcode = 'invalid_parameter_value';
  end if;

  if v_inv.expires_at <= now() then
    raise exception 'invitation has expired'
      using errcode = 'invalid_parameter_value';
  end if;

  if v_email is null or lower(v_inv.email) <> lower(v_email) then
    raise exception 'invitation was issued to a different email address'
      using errcode = 'insufficient_privilege';
  end if;

  insert into public.memberships (org_id, user_id, role)
  values (v_inv.org_id, v_uid, v_inv.role)
  on conflict (org_id, user_id) do update
    set role = excluded.role
  returning * into v_membership;

  update public.invitations
  set accepted_at = now(),
      accepted_by = v_uid
  where id = v_inv.id;

  return v_membership;
end;
$$;

revoke all on public.invitations from anon;
grant select, insert, update, delete on public.invitations to authenticated;

revoke execute on function public.accept_invitation(text) from public;
grant execute on function public.accept_invitation(text) to authenticated, service_role;
